package com.example.tmdb.core.ui.theme.designsystem

import androidx.compose.runtime.Immutable
import com.example.tmdb.R

@Immutable
data class TMDBIcons(
    val alert: Int = R.drawable.alert,
    val arrowBack: Int = R.drawable.arrowback,
    val arrowDownward: Int = R.drawable.arrowdownward,
    val audio: Int = R.drawable.audio,
    val audio2: Int = R.drawable.audio2,
    val calendar: Int = R.drawable.calendar,
    val clock: Int = R.drawable.clock,
    val closedCaption: Int = R.drawable.closed_caption,
    val devices: Int = R.drawable.devices,
    val download: Int = R.drawable.download,
    val download2: Int = R.drawable.download2,
    val downloadOffline: Int = R.drawable.downloadforofflineblack,
    val edit: Int = R.drawable.edit,
    val edit2: Int = R.drawable.edit2,
    val eyyOff: Int = R.drawable.eyeoff,
    val film: Int = R.drawable.film,
    val finish: Int = R.drawable.finish,
    val folder: Int = R.drawable.folder,
    val fullScreen: Int = R.drawable.fullscreen,
    val hd: Int = R.drawable.hd,
    val heart: Int = R.drawable.heart,
    val home: Int = R.drawable.home,
    val layer: Int = R.drawable.layer,
    val globe: Int = R.drawable.globe,
    val noResult: Int = R.drawable.noresults,
    val notification: Int = R.drawable.notification,
    val padLock: Int = R.drawable.padlock,
    val pause: Int = R.drawable.pause,
    val person: Int = R.drawable.person,
    val person2: Int = R.drawable.person2,
    val profile: Int = R.drawable.profile,
    val question: Int = R.drawable.question,
    val question2: Int = R.drawable.question2,
    val remove: Int = R.drawable.remove,
    val search: Int = R.drawable.search,
    val settings: Int = R.drawable.settings,
    val share: Int = R.drawable.share,
    val shield: Int = R.drawable.shield,
    val star: Int = R.drawable.star,
    val tick: Int = R.drawable.tick,
    val trashBin: Int = R.drawable.trashbin,
    val workspace: Int = R.drawable.workspacepremiumblack
)